version: "3.8"

services:
    n-body-simulations:
        container_name: N-Body Simulations
        image: n-body-simulations
        build:
            context: .
            dockerfile: Dockerfile
        command:
            bash -c "conda activate n-body-env && python /usr/N-Body-Simulations/n_body_simulations/startup.py"
