package:
  name: n-body-simulations
  version: 1.1.0

source:
  path: ../

requirements:
  build:
    - cmake
    - cycler
    - gtest
    - pillow
    - pybind11
    - python {{ python }}
    - setuptools

  host:
    - matplotlib
    - python {{ python }}
    - pyqt
    - qtawesome

test:
  imports:
    - n_body_simulations

about:
  home: https://github.com/robertapplin/N-Body-Simulations
  license: MIT
  summary: A QWidget used for simulating a gravitational system of N bodies in two dimensions.
