package:
  name: n-body-simulations
  version: 1.1.0

source:
  path: ../

requirements:
  build:
    - cmake
    - gmock {{ gmock }}
    - gtest {{ gtest }}
    - ninja
    - pybind11
    - python {{ python }}
    - setuptools

  host:
    - pybind11
    - python {{ python }}
    - pyqt
    - pyside2
    - qt-main {{ qt_main }}
    - qtawesome

  run:
    - matplotlib
    - python {{ python }}
    - pyqt
    - pyside2
    - qt-main {{ qt_main }}
    - qtawesome

test:
  imports:
    - n_body_simulations.startup

about:
  home: https://github.com/robertapplin/N-Body-Simulations
  license: MIT
  summary: A QWidget used for simulating a gravitational system of N bodies in two dimensions.
