# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.fSetup = QtWidgets.QFrame(self.centralwidget)
        self.fSetup.setObjectName("fSetup")
        self.gridLayout = QtWidgets.QGridLayout(self.fSetup)
        self.gridLayout.setObjectName("gridLayout")
        self.pbPlayPause = QtWidgets.QPushButton(self.fSetup)
        self.pbPlayPause.setObjectName("pbPlayPause")
        self.gridLayout.addWidget(self.pbPlayPause, 2, 0, 1, 3)
        self.cbBodyNames = QtWidgets.QComboBox(self.fSetup)
        self.cbBodyNames.setMinimumSize(QtCore.QSize(0, 21))
        self.cbBodyNames.setMaximumSize(QtCore.QSize(16777215, 21))
        self.cbBodyNames.setObjectName("cbBodyNames")
        self.cbBodyNames.addItem("")
        self.gridLayout.addWidget(self.cbBodyNames, 0, 0, 1, 1)
        self.pbAddBody = QtWidgets.QPushButton(self.fSetup)
        self.pbAddBody.setMinimumSize(QtCore.QSize(23, 23))
        self.pbAddBody.setMaximumSize(QtCore.QSize(23, 23))
        self.pbAddBody.setObjectName("pbAddBody")
        self.gridLayout.addWidget(self.pbAddBody, 0, 2, 1, 1)
        self.pbRemoveBody = QtWidgets.QPushButton(self.fSetup)
        self.pbRemoveBody.setMinimumSize(QtCore.QSize(23, 23))
        self.pbRemoveBody.setMaximumSize(QtCore.QSize(23, 23))
        self.pbRemoveBody.setObjectName("pbRemoveBody")
        self.gridLayout.addWidget(self.pbRemoveBody, 0, 1, 1, 1)
        self.horizontalLayout.addWidget(self.fSetup)
        self.plotLayout = QtWidgets.QGridLayout()
        self.plotLayout.setObjectName("plotLayout")
        self.horizontalLayout.addLayout(self.plotLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "N-Body Simulations"))
        self.pbPlayPause.setToolTip(_translate("MainWindow", "Play/Pause"))
        self.pbPlayPause.setText(_translate("MainWindow", "Play"))
        self.cbBodyNames.setItemText(0, _translate("MainWindow", "Sun"))
        self.pbAddBody.setText(_translate("MainWindow", "+"))
        self.pbRemoveBody.setText(_translate("MainWindow", "Bin"))
