# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_body_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddBodyDialog(object):
    def setupUi(self, AddBodyDialog):
        AddBodyDialog.setObjectName("AddBodyDialog")
        AddBodyDialog.resize(329, 170)
        self.gridLayout = QtWidgets.QGridLayout(AddBodyDialog)
        self.gridLayout.setContentsMargins(20, 20, 20, -1)
        self.gridLayout.setObjectName("gridLayout")
        self.lbBodyName = QtWidgets.QLabel(AddBodyDialog)
        self.lbBodyName.setObjectName("lbBodyName")
        self.gridLayout.addWidget(self.lbBodyName, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 4, 1, 1, 1)
        self.fAddCancel = QtWidgets.QFrame(AddBodyDialog)
        self.fAddCancel.setMinimumSize(QtCore.QSize(30, 0))
        self.fAddCancel.setObjectName("fAddCancel")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.fAddCancel)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pbAdd = QtWidgets.QPushButton(self.fAddCancel)
        self.pbAdd.setObjectName("pbAdd")
        self.horizontalLayout.addWidget(self.pbAdd)
        self.pbCancel = QtWidgets.QPushButton(self.fAddCancel)
        self.pbCancel.setObjectName("pbCancel")
        self.horizontalLayout.addWidget(self.pbCancel)
        self.gridLayout.addWidget(self.fAddCancel, 7, 0, 1, 2)
        self.leBodyName = QtWidgets.QLineEdit(AddBodyDialog)
        self.leBodyName.setMinimumSize(QtCore.QSize(20, 0))
        self.leBodyName.setObjectName("leBodyName")
        self.gridLayout.addWidget(self.leBodyName, 0, 1, 1, 1)
        self.dsbXPosition = QtWidgets.QDoubleSpinBox(AddBodyDialog)
        self.dsbXPosition.setMinimumSize(QtCore.QSize(20, 0))
        self.dsbXPosition.setMinimum(-100.0)
        self.dsbXPosition.setMaximum(100.0)
        self.dsbXPosition.setObjectName("dsbXPosition")
        self.gridLayout.addWidget(self.dsbXPosition, 2, 1, 1, 1)
        self.dsbMass = QtWidgets.QDoubleSpinBox(AddBodyDialog)
        self.dsbMass.setMinimumSize(QtCore.QSize(20, 0))
        self.dsbMass.setMinimum(0.01)
        self.dsbMass.setSingleStep(0.1)
        self.dsbMass.setObjectName("dsbMass")
        self.gridLayout.addWidget(self.dsbMass, 1, 1, 1, 1)
        self.dsbYPosition = QtWidgets.QDoubleSpinBox(AddBodyDialog)
        self.dsbYPosition.setMinimumSize(QtCore.QSize(20, 0))
        self.dsbYPosition.setMinimum(-100.0)
        self.dsbYPosition.setMaximum(100.0)
        self.dsbYPosition.setObjectName("dsbYPosition")
        self.gridLayout.addWidget(self.dsbYPosition, 3, 1, 1, 1)
        self.lbMass = QtWidgets.QLabel(AddBodyDialog)
        self.lbMass.setObjectName("lbMass")
        self.gridLayout.addWidget(self.lbMass, 1, 0, 1, 1)
        self.lbXPosition = QtWidgets.QLabel(AddBodyDialog)
        self.lbXPosition.setObjectName("lbXPosition")
        self.gridLayout.addWidget(self.lbXPosition, 2, 0, 1, 1)
        self.lbYPosition = QtWidgets.QLabel(AddBodyDialog)
        self.lbYPosition.setObjectName("lbYPosition")
        self.gridLayout.addWidget(self.lbYPosition, 3, 0, 1, 1)

        self.retranslateUi(AddBodyDialog)
        QtCore.QMetaObject.connectSlotsByName(AddBodyDialog)

    def retranslateUi(self, AddBodyDialog):
        _translate = QtCore.QCoreApplication.translate
        AddBodyDialog.setWindowTitle(_translate("AddBodyDialog", "Add Body Dialog"))
        self.lbBodyName.setText(_translate("AddBodyDialog", "Name: "))
        self.pbAdd.setText(_translate("AddBodyDialog", "Add"))
        self.pbCancel.setText(_translate("AddBodyDialog", "Cancel"))
        self.dsbXPosition.setSuffix(_translate("AddBodyDialog", " au"))
        self.dsbMass.setSuffix(_translate("AddBodyDialog", " M*"))
        self.dsbYPosition.setSuffix(_translate("AddBodyDialog", " au"))
        self.lbMass.setText(_translate("AddBodyDialog", "Mass: "))
        self.lbXPosition.setText(_translate("AddBodyDialog", "X: "))
        self.lbYPosition.setText(_translate("AddBodyDialog", "Y: "))
