# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NBodySimulator(object):
    def setupUi(self, NBodySimulator):
        NBodySimulator.setObjectName("NBodySimulator")
        NBodySimulator.resize(658, 963)
        self.verticalLayout = QtWidgets.QVBoxLayout(NBodySimulator)
        self.verticalLayout.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.fSetup = QtWidgets.QFrame(NBodySimulator)
        self.fSetup.setObjectName("fSetup")
        self.gridLayout = QtWidgets.QGridLayout(self.fSetup)
        self.gridLayout.setContentsMargins(0, -1, 0, -1)
        self.gridLayout.setObjectName("gridLayout")
        self.pbInteractiveMode = QtWidgets.QPushButton(self.fSetup)
        self.pbInteractiveMode.setMinimumSize(QtCore.QSize(30, 30))
        self.pbInteractiveMode.setMaximumSize(QtCore.QSize(30, 30))
        self.pbInteractiveMode.setText("")
        self.pbInteractiveMode.setCheckable(True)
        self.pbInteractiveMode.setChecked(True)
        self.pbInteractiveMode.setObjectName("pbInteractiveMode")
        self.gridLayout.addWidget(self.pbInteractiveMode, 0, 7, 1, 1)
        self.tbTimeSettings = QtWidgets.QToolButton(self.fSetup)
        self.tbTimeSettings.setMinimumSize(QtCore.QSize(30, 30))
        self.tbTimeSettings.setMaximumSize(QtCore.QSize(30, 30))
        self.tbTimeSettings.setText("")
        self.tbTimeSettings.setObjectName("tbTimeSettings")
        self.gridLayout.addWidget(self.tbTimeSettings, 0, 3, 1, 1)
        self.pbPlayPause = QtWidgets.QPushButton(self.fSetup)
        self.pbPlayPause.setMinimumSize(QtCore.QSize(30, 30))
        self.pbPlayPause.setMaximumSize(QtCore.QSize(30, 30))
        self.pbPlayPause.setText("")
        self.pbPlayPause.setObjectName("pbPlayPause")
        self.gridLayout.addWidget(self.pbPlayPause, 0, 10, 1, 1)
        self.line = QtWidgets.QFrame(self.fSetup)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 0, 8, 1, 1)
        self.tbAddBody = QtWidgets.QToolButton(self.fSetup)
        self.tbAddBody.setMinimumSize(QtCore.QSize(30, 30))
        self.tbAddBody.setMaximumSize(QtCore.QSize(30, 30))
        self.tbAddBody.setText("")
        self.tbAddBody.setObjectName("tbAddBody")
        self.gridLayout.addWidget(self.tbAddBody, 0, 2, 1, 1)
        self.pbStop = QtWidgets.QPushButton(self.fSetup)
        self.pbStop.setMinimumSize(QtCore.QSize(30, 30))
        self.pbStop.setMaximumSize(QtCore.QSize(30, 30))
        self.pbStop.setText("")
        self.pbStop.setObjectName("pbStop")
        self.gridLayout.addWidget(self.pbStop, 0, 9, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.fSetup)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 0, 4, 1, 1)
        self.pbRemoveBody = QtWidgets.QPushButton(self.fSetup)
        self.pbRemoveBody.setMinimumSize(QtCore.QSize(30, 30))
        self.pbRemoveBody.setMaximumSize(QtCore.QSize(30, 30))
        self.pbRemoveBody.setText("")
        self.pbRemoveBody.setObjectName("pbRemoveBody")
        self.gridLayout.addWidget(self.pbRemoveBody, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 0, 1, 1)
        self.tbPlotOptions = QtWidgets.QToolButton(self.fSetup)
        self.tbPlotOptions.setMinimumSize(QtCore.QSize(30, 30))
        self.tbPlotOptions.setMaximumSize(QtCore.QSize(30, 30))
        self.tbPlotOptions.setText("")
        self.tbPlotOptions.setObjectName("tbPlotOptions")
        self.gridLayout.addWidget(self.tbPlotOptions, 0, 6, 1, 1)
        self.verticalLayout.addWidget(self.fSetup)

        self.retranslateUi(NBodySimulator)
        QtCore.QMetaObject.connectSlotsByName(NBodySimulator)

    def retranslateUi(self, NBodySimulator):
        _translate = QtCore.QCoreApplication.translate
        NBodySimulator.setWindowTitle(_translate("NBodySimulator", "N-Body Simulator"))
        self.pbInteractiveMode.setToolTip(_translate("NBodySimulator", "Interactive Mode"))
        self.tbTimeSettings.setToolTip(_translate("NBodySimulator", "Time Settings"))
        self.pbPlayPause.setToolTip(_translate("NBodySimulator", "Play"))
        self.tbAddBody.setToolTip(_translate("NBodySimulator", "Add Body Options"))
        self.pbStop.setToolTip(_translate("NBodySimulator", "Stop"))
        self.pbRemoveBody.setToolTip(_translate("NBodySimulator", "Remove Selected Body"))
        self.tbPlotOptions.setToolTip(_translate("NBodySimulator", "Plot Options"))
