name: Clang Format

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Clang Format
      uses: DoozyX/clang-format-lint-action@v0.10
      with:
        source: '.'
        extensions: 'h,cpp'
        clangFormatVersion: 11
        style: chromium
