name: Check Dependencies

on:
  pull_request:  # Temporary
    branches: [ main ]  # Temporary
  schedule:
    - cron:  '0 12 * * FRI'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2.2.0
      with:
        miniforge-version: latest
        miniforge-variant: Mambaforge
        activate-environment: test-env
        environment-file: conda/testing.yml
        python-version: 3.8
        auto-activate-base: false

    - name: Rename downloaded file
      run: |
        source $PWD/rename.sh

    - name: Archive code coverage results
      uses: actions/upload-artifact@v3
      with:
        name: code-coverage-report
        path: uploads/dependencies.txt
