name: Unit Tests

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Setup Miniconda
      uses: s-weigand/setup-conda@v1
    - name: Install dependencies
      run: |
        conda install -c anaconda pyqt
        conda install -c conda-forge pybind11 pytest
    - name: Build and Install Packages
      uses: ashutoshvarma/action-cmake-build@master
      with:
        build-dir: ${{ runner.workspace }}/build
        cc: gcc
        cxx: g++
        build-type: Release
        configure-options: -DCMAKE_C_FLAGS=-w32 -DPYTHON_LIBRARY_DIR=C:/Miniconda/lib/site-packages/ -DPYTHON_EXECUTABLE=C:/Miniconda/python.exe
        install-build: true  
    - name: Run Python Unit Tests
      run: |
        pytest tests/unit_tests/python/
