name: Unit Tests

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Setup Miniconda
      uses: s-weigand/setup-conda@v1
    - name: Install Dependencies
      run: |
        conda install -c anaconda pyqt
        conda install -c conda-forge pybind11 pytest
    - name: Build Project
      run: |
        mkdir build
        cd build
        cmake .. -DPYTHON_LIBRARY_DIR=C:/Miniconda/lib/site-packages/ -DPYTHON_EXECUTABLE=C:/Miniconda/python.exe
        cmake --build . --config Release
    - name: Install NBodySimulations as a Python Module
      run: |
        cd build
        cmake --install .
    - name: Run Cpp Unit Tests
      run: |
        cd build/tests/unit_tests/cpp/Release
        ./NBodySimulationsUnitTests.exe
    - name: Run Python Unit Tests
      run: |
        pytest tests/unit_tests/python/
